name: tempus_victa
description: Tempus Victa - framework baseline + tasks voice capture v2
publish_to: "none"
version: 0.0.2+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  path_provider: ^2.1.4
  uuid: ^4.5.1
  record: ^6.2.0
  just_audio: ^0.9.40
  speech_to_text: ^7.0.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
